{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "60b1189a_f66b7393",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 47
      },
      "writtenOn": "2021-11-18T13:42:15Z",
      "side": 1,
      "message": "Now I cannot reproduce the error either.",
      "revId": "dadd1d19f94a400e4b05075e2832ae42cd654c0f",
      "serverId": "626241b7-b7d0-4197-b843-1ee23887649c"
    }
  ]
}